#!/bin/bash

# disk="disk4s1"
#
# # unmount if necessary
# sudo diskutil unmount /dev/$disk
# # mount with ntfs-3g
# sudo mkdir /Volumes/NTFS
# sudo ntfs-3g /dev/$disk /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache
# # alternatively...
# # sudo mount_ntfs /dev/$disk /Volumes/NTFSexit
# open /Volumes/NTFS
# # exit


# List available disks and their identifiers
diskutil list

echo "NTFS probably:"
diskutil list | grep -i "ntfs"


# Prompt the user to select a disk by identifier
read -p "Enter the disk identifier you want to mount (e.g., disk2s1): " selected_disk

# Check if the selected disk identifier is valid
if [ -z "$selected_disk" ]; then
    echo "Invalid disk identifier. Exiting."
    exit 1
fi

# Get the name of the selected disk
selected_disk_name=$(diskutil info "/dev/${selected_disk}" | grep "Volume Name" | awk '{print $3}')


# echo ">>$selected_disk_name<<"
# exit

# Check if the selected disk name is empty
if [ -z "$selected_disk_name" ]; then
    echo "Failed to get the disk name. Using a default name."
    selected_disk_name="MyDisk"
else
    echo "Selected disk name: $selected_disk_name"   
        
    # Step 1: Unmount the NTFS Drive
    sudo umount "/Volumes/${selected_disk_name}"

    # Step 2: Create a Mount Point
    sudo mkdir "/Volumes/${selected_disk_name}-ntfs-new"

    # Step 3: Mount the Selected Disk with Write Permissions
    # sudo mount -t ntfs-3g -o rw,auto,nobrowse /dev/${selected_disk} "/Volumes/${selected_disk_name}-ntfs-new"
    sudo ntfs-3g /dev/$selected_disk "/Volumes/${selected_disk_name}-ntfs-new" -o local -o allow_other -o auto_xattr -o auto_cache

    # Step 4: Open the Mounted Drive
    open "/Volumes/${selected_disk_name}-ntfs-new"

    # Wait for 'q' to be pressed to unmount and eject
    read -n 1 -s -r -p "Press 'q' to unmount and eject the drive, or any other key to exit..."

    if [ "$REPLY" == "q" ]; then
        # Unmount the drive
        sudo umount "/Volumes/${selected_disk_name}-ntfs-new"
        
        # Eject the drive
        diskutil eject "/dev/${selected_disk}"
        echo "Drive unmounted and ejected."
    fi 
fi
