#!/usr/bin/env bash

# sudo umount /Volumes/Transcend
# sudo mkdir /Volumes/disk2s1
# sudo mount -t ntfs -o rw,auto,nobrowse /dev/disk2s1 /Volumes/disk2s1
# open /Volumes/disk2s1
disk="disk5s1"

sudo diskutil unmount /dev/$disk
sudo mkdir /Volumes/NTFSDrive
sudo /usr/local/sbin/mount_ntfs /dev/$disk /Volumes/NTFSDrive
open /Volumes/NTFSDrive
